var surveyquestions = [
'Have you ever collected rocks?',
'Have you ever taken a Geology class?',
'If you have taken a Geology class, how long ago did you take it?',
'If you have taken a Geology class, at what education level did you take it?',
'Have you ever taken a class in which Geology or rock types was a unit?',
'Have you ever worked in a job in which knowledge about rocks was important?',
'What would you say is your previous experience level with identifying rocks?',
'It upsets me to go into a situation without knowing what I can expect from it.',
'I am not bothered by things that interrupt my daily routine.',
'I enjoy having a clear and structured mode of life.',
'I like to have a place for everything and everything in its place.',
'I enjoy being spontaneous.',
'I find that a well-ordered life with regular hours makes my life tedious.',
'I don’t like situations that are uncertain.',
'I hate to change my plans at the last minute.',
'I hate to be with people who are unpredictable.',
'I find that a consistent routine enables me to enjoy life more.',
'I find the exhilaration of being in unpredictable situations.',
'I become uncomfortable when the rules in a situation are not clear.'
]

var listimagenames = [
 'images/Night Vision Context/I_Granite/I_Granite_01_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_02_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_03_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_04_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_05_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_06_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_07_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_08_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_09_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_10_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_11_NV.png',
 'images/Night Vision Context/I_Granite/I_Granite_12_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_01_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_02_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_03_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_04_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_05_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_06_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_07_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_08_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_09_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_10_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_11_NV.png',
 'images/Night Vision Context/I_Obsidian/I_Obsidian_12_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_01_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_02_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_03_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_04_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_05_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_06_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_07_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_08_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_09_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_10_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_11_NV.png',
 'images/Night Vision Context/I_Pegmatite/I_Pegmatite_12_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_01_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_02_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_03_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_04_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_05_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_06_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_07_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_08_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_09_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_10_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_11_NV.png',
 'images/Night Vision Context/I_Pumice/I_Pumice_12_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_01_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_02_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_03_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_04_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_05_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_06_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_07_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_08_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_09_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_10_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_11_NV.png',
 'images/Night Vision Context/M_Amphibolite/M_Amphibolite_12_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_01_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_02_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_03_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_04_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_05_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_06_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_07_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_08_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_09_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_10_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_11_NV.png',
 'images/Night Vision Context/M_Gneiss/M_Gneiss_12_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_01_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_02_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_03_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_04_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_05_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_06_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_07_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_08_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_09_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_10_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_11_NV.png',
 'images/Night Vision Context/M_Marble/M_Marble_12_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_01_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_02_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_03_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_04_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_05_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_06_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_07_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_08_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_09_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_10_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_11_NV.png',
 'images/Night Vision Context/M_Slate/M_Slate_12_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_01_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_02_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_03_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_04_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_05_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_06_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_07_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_08_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_09_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_10_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_11_NV.png',
 'images/Night Vision Context/S_Breccia/S_Breccia_12_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_01_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_02_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_03_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_04_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_05_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_06_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_07_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_08_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_09_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_10_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_11_NV.png',
 'images/Night Vision Context/S_Conglomerate/S_Conglomerate_12_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_01_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_02_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_03_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_04_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_05_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_06_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_07_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_08_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_09_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_10_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_11_NV.png',
 'images/Night Vision Context/S_Rock Gypsum/S_RockGypsum_12_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_01_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_02_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_03_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_04_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_05_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_06_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_07_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_08_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_09_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_10_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_11_NV.png',
 'images/Night Vision Context/S_Sandstone/S_Sandstone_12_NV.png',
 'images/Perfect World Context/I_Granite/I_Granite_01.png',
 'images/Perfect World Context/I_Granite/I_Granite_02.png',
 'images/Perfect World Context/I_Granite/I_Granite_03.png',
 'images/Perfect World Context/I_Granite/I_Granite_04.png',
 'images/Perfect World Context/I_Granite/I_Granite_05.png',
 'images/Perfect World Context/I_Granite/I_Granite_06.png',
 'images/Perfect World Context/I_Granite/I_Granite_07.png',
 'images/Perfect World Context/I_Granite/I_Granite_08.png',
 'images/Perfect World Context/I_Granite/I_Granite_09.png',
 'images/Perfect World Context/I_Granite/I_Granite_10.png',
 'images/Perfect World Context/I_Granite/I_Granite_11.png',
 'images/Perfect World Context/I_Granite/I_Granite_12.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_01.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_02.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_03.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_04.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_05.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_06.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_07.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_08.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_09.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_10.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_11.png',
 'images/Perfect World Context/I_Obsidian/I_Obsidian_12.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_01.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_02.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_03.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_04.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_05.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_06.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_07.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_08.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_09.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_10.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_11.png',
 'images/Perfect World Context/I_Pegmatite/I_Pegmatite_12.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_01.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_02.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_03.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_04.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_05.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_06.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_07.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_08.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_09.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_10.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_11.png',
 'images/Perfect World Context/I_Pumice/I_Pumice_12.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_01.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_02.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_03.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_04.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_05.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_06.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_07.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_08.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_09.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_10.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_11.png',
 'images/Perfect World Context/M_Amphibolite/M_Amphibolite_12.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_01.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_02.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_03.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_04.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_05.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_06.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_07.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_08.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_09.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_10.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_11.png',
 'images/Perfect World Context/M_Gneiss/M_Gneiss_12.png',
 'images/Perfect World Context/M_Marble/M_Marble_01.png',
 'images/Perfect World Context/M_Marble/M_Marble_02.png',
 'images/Perfect World Context/M_Marble/M_Marble_03.png',
 'images/Perfect World Context/M_Marble/M_Marble_04.png',
 'images/Perfect World Context/M_Marble/M_Marble_05.png',
 'images/Perfect World Context/M_Marble/M_Marble_06.png',
 'images/Perfect World Context/M_Marble/M_Marble_07.png',
 'images/Perfect World Context/M_Marble/M_Marble_08.png',
 'images/Perfect World Context/M_Marble/M_Marble_09.png',
 'images/Perfect World Context/M_Marble/M_Marble_10.png',
 'images/Perfect World Context/M_Marble/M_Marble_11.png',
 'images/Perfect World Context/M_Marble/M_Marble_12.png',
 'images/Perfect World Context/M_Slate/M_Slate_01.png',
 'images/Perfect World Context/M_Slate/M_Slate_02.png',
 'images/Perfect World Context/M_Slate/M_Slate_03.png',
 'images/Perfect World Context/M_Slate/M_Slate_04.png',
 'images/Perfect World Context/M_Slate/M_Slate_05.png',
 'images/Perfect World Context/M_Slate/M_Slate_06.png',
 'images/Perfect World Context/M_Slate/M_Slate_07.png',
 'images/Perfect World Context/M_Slate/M_Slate_08.png',
 'images/Perfect World Context/M_Slate/M_Slate_09.png',
 'images/Perfect World Context/M_Slate/M_Slate_10.png',
 'images/Perfect World Context/M_Slate/M_Slate_11.png',
 'images/Perfect World Context/M_Slate/M_Slate_12.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_01.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_02.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_03.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_04.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_05.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_06.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_07.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_08.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_09.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_10.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_11.png',
 'images/Perfect World Context/S_Breccia/S_Breccia_12.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_01.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_02.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_03.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_04.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_05.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_06.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_07.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_08.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_09.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_10.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_11.png',
 'images/Perfect World Context/S_Conglomerate/S_Conglomerate_12.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_01.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_02.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_03.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_04.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_05.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_06.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_07.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_08.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_09.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_10.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_11.png',
 'images/Perfect World Context/S_Rock Gypsum/S_Rock Gypsum_12.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_01.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_02.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_03.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_04.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_05.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_06.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_07.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_08.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_09.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_10.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_11.png',
 'images/Perfect World Context/S_Sandstone/S_Sandstone_12.png',
 'images/Water Context/I_Granite/I_Granite_01.png',
 'images/Water Context/I_Granite/I_Granite_02.png',
 'images/Water Context/I_Granite/I_Granite_03.png',
 'images/Water Context/I_Granite/I_Granite_04.png',
 'images/Water Context/I_Granite/I_Granite_05.png',
 'images/Water Context/I_Granite/I_Granite_06.png',
 'images/Water Context/I_Granite/I_Granite_07.png',
 'images/Water Context/I_Granite/I_Granite_08.png',
 'images/Water Context/I_Granite/I_Granite_09.png',
 'images/Water Context/I_Granite/I_Granite_10.png',
 'images/Water Context/I_Granite/I_Granite_11.png',
 'images/Water Context/I_Granite/I_Granite_12.png',
 'images/Water Context/I_Obsidian/I_Obsidian_01_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_02_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_03_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_04_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_05_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_06_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_07_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_08_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_09_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_10_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_11_W.png',
 'images/Water Context/I_Obsidian/I_Obsidian_12_W.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_01.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_02.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_03.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_04.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_05.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_06.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_07.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_08.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_09.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_10.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_11.png',
 'images/Water Context/I_Pegmatite/I_Pegmatite_12.png',
 'images/Water Context/I_Pumice/I_Pumice_01_W.png',
 'images/Water Context/I_Pumice/I_Pumice_02_W.png',
 'images/Water Context/I_Pumice/I_Pumice_03_W.png',
 'images/Water Context/I_Pumice/I_Pumice_04_W.png',
 'images/Water Context/I_Pumice/I_Pumice_05_W.png',
 'images/Water Context/I_Pumice/I_Pumice_06_W.png',
 'images/Water Context/I_Pumice/I_Pumice_07_W.png',
 'images/Water Context/I_Pumice/I_Pumice_08_W.png',
 'images/Water Context/I_Pumice/I_Pumice_09_W.png',
 'images/Water Context/I_Pumice/I_Pumice_10_W.png',
 'images/Water Context/I_Pumice/I_Pumice_11_W.png',
 'images/Water Context/I_Pumice/I_Pumice_12_W.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_01.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_02.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_03.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_04.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_05.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_06.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_07.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_08.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_09.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_10.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_11.png',
 'images/Water Context/M_Amphibolite/M_Amphibolite_12.png',
 'images/Water Context/M_Gneiss/M_Gneiss_01.png',
 'images/Water Context/M_Gneiss/M_Gneiss_02.png',
 'images/Water Context/M_Gneiss/M_Gneiss_03.png',
 'images/Water Context/M_Gneiss/M_Gneiss_04.png',
 'images/Water Context/M_Gneiss/M_Gneiss_05.png',
 'images/Water Context/M_Gneiss/M_Gneiss_06.png',
 'images/Water Context/M_Gneiss/M_Gneiss_07.png',
 'images/Water Context/M_Gneiss/M_Gneiss_08.png',
 'images/Water Context/M_Gneiss/M_Gneiss_09.png',
 'images/Water Context/M_Gneiss/M_Gneiss_10.png',
 'images/Water Context/M_Gneiss/M_Gneiss_11.png',
 'images/Water Context/M_Gneiss/M_Gneiss_12.png',
 'images/Water Context/M_Marble/M_Marble_01.png',
 'images/Water Context/M_Marble/M_Marble_02.png',
 'images/Water Context/M_Marble/M_Marble_03.png',
 'images/Water Context/M_Marble/M_Marble_04.png',
 'images/Water Context/M_Marble/M_Marble_05.png',
 'images/Water Context/M_Marble/M_Marble_06.png',
 'images/Water Context/M_Marble/M_Marble_07.png',
 'images/Water Context/M_Marble/M_Marble_08.png',
 'images/Water Context/M_Marble/M_Marble_09.png',
 'images/Water Context/M_Marble/M_Marble_10.png',
 'images/Water Context/M_Marble/M_Marble_11.png',
 'images/Water Context/M_Marble/M_Marble_12.png',
 'images/Water Context/M_Slate/M_Slate_01.png',
 'images/Water Context/M_Slate/M_Slate_02.png',
 'images/Water Context/M_Slate/M_Slate_03.png',
 'images/Water Context/M_Slate/M_Slate_04.png',
 'images/Water Context/M_Slate/M_Slate_05.png',
 'images/Water Context/M_Slate/M_Slate_06.png',
 'images/Water Context/M_Slate/M_Slate_07.png',
 'images/Water Context/M_Slate/M_Slate_08.png',
 'images/Water Context/M_Slate/M_Slate_09.png',
 'images/Water Context/M_Slate/M_Slate_10.png',
 'images/Water Context/M_Slate/M_Slate_11.png',
 'images/Water Context/M_Slate/M_Slate_12.png',
 'images/Water Context/S_Breccia/S_Breccia_01_W.png',
 'images/Water Context/S_Breccia/S_Breccia_02_W.png',
 'images/Water Context/S_Breccia/S_Breccia_03_W.png',
 'images/Water Context/S_Breccia/S_Breccia_04_W.png',
 'images/Water Context/S_Breccia/S_Breccia_05_W.png',
 'images/Water Context/S_Breccia/S_Breccia_06_W.png',
 'images/Water Context/S_Breccia/S_Breccia_07_W.png',
 'images/Water Context/S_Breccia/S_Breccia_08_W.png',
 'images/Water Context/S_Breccia/S_Breccia_09_W.png',
 'images/Water Context/S_Breccia/S_Breccia_10_W.png',
 'images/Water Context/S_Breccia/S_Breccia_11_W.png',
 'images/Water Context/S_Breccia/S_Breccia_12_W.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_01.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_02.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_03.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_04.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_05.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_06.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_07.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_08.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_09.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_10.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_11.png',
 'images/Water Context/S_Conglomerate/S_Conglomerate_12.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_01.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_02.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_03.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_04.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_05.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_06.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_07.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_08.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_09.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_10.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_11.png',
 'images/Water Context/S_Rock Gypsum/S_Rock Gypsum_12.png',
 'images/Water Context/S_Sandstone/S_Sandstone_01_W.png',
 'images/Water Context/S_Sandstone/S_Sandstone_02_W.png',
 'images/Water Context/S_Sandstone/S_Sandstone_03.png',
 'images/Water Context/S_Sandstone/S_Sandstone_04.png',
 'images/Water Context/S_Sandstone/S_Sandstone_05.png',
 'images/Water Context/S_Sandstone/S_Sandstone_06.png',
 'images/Water Context/S_Sandstone/S_Sandstone_07.png',
 'images/Water Context/S_Sandstone/S_Sandstone_08.png',
 'images/Water Context/S_Sandstone/S_Sandstone_09.png',
 'images/Water Context/S_Sandstone/S_Sandstone_10.png',
 'images/Water Context/S_Sandstone/S_Sandstone_11.png',
 'images/Water Context/S_Sandstone/S_Sandstone_12.png'
]

var image_context = [
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2]

var image_version = [
  1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12]

var image_type = [
  1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
8,
8,
8,
8,
8,
8,
8,
8,
8,
8,
8,
8,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
11,
11,
11,
11,
11,
11,
11,
11,
11,
11,
11,
11,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
8,
8,
8,
8,
8,
8,
8,
8,
8,
8,
8,
8,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
11,
11,
11,
11,
11,
11,
11,
11,
11,
11,
11,
11,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
3,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
4,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
7,
8,
8,
8,
8,
8,
8,
8,
8,
8,
8,
8,
8,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
11,
11,
11,
11,
11,
11,
11,
11,
11,
11,
11,
11,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12]
